### ISSUE TITLE
首页 README 里有一个死死链

### ISSUE THREAD

**Issue by Lohoyo** [wanwu/san-project#9]
我不是很确定它应该指到哪里，所以提了个 Issues 而不是 pr。

![image](https://user-images.githubusercontent.com/28821810/117654487-64f0a480-b1c8-11eb-945b-ee386d7e2559.png)
https://github.com/ksky521/san-project

**Comment by ksky521** [comment]
删掉了

**Comment by Lohoyo** [comment]
> 删掉了

我看了下，好像还在诶。
